name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3  # Å© Ç±Ç±Ç v4.3.3 Ç…ïœçXÅI
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
