name: FTP Deploy

on:
  push:
    branches:
      - main  # ← GitHubのブランチ名が "main" ならそのまま、"master" の場合は変更

jobs:
  ftp-deploy:
    name: Upload to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /web/AI-p/
